spring:
  zipkin:
    baseUrl: http://zipkin.istio-system.svc:9411
    sender:
      type: web
  sleuth:
    opentracing:
      enabled: true
    baggage:
      correlation-enabled: true
      remote-fields: x-request-id, x-access-token, x-source-system, x-source-application,
        x-source-business-process, x-source-business-activity
      correlation-fields: x-request-id, x-access-token, x-source-system, x-source-application,
            x-source-business-process, x-source-business-activity

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState, livenessResponseCheck
        readiness:
          include: readinessState, db, kafka
    loggers:
      enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

probes:
  liveness:
    failureThreshold: 10

datafactory-excerpt-ceph:
  bucket: ${DATAFACTORY_EXCERPT_CEPH_BUCKET_NAME}

data-platform:
  kafka:
    group-id: excerpt-worker
    trusted-packages:
      - com.epam.digital.data.platform.excerpt.model
    error-handler:
      initial-interval: 1500
      max-elapsede-time: 6000
      multiplier: 2
    topic: generate-excerpt
