apiVersion: v1
kind: ConfigMap
metadata:
  name: excerpt-worker-properties
data:
  config.yaml: |-
    data-platform:
      datasource:
        url: jdbc:postgresql://{{.Values.db.url}}:{{.Values.db.port}}/{{.Values.db.name}}
        connection-timeout: {{.Values.db.connectionTimeout}}
      kafka:
        bootstrap: {{ .Values.kafka.service }}

    datafactory-excerpt-ceph:
      http-endpoint: {{ .Values.datafactoryExcerptCeph.httpEndpoint }}
      bucketName: {{ .Values.datafactoryExcerptCeph.bucketName }}

    s3:
      config:
        client: {{ .Values.s3.config.client | toYaml | nindent 10 }}
        options: {{ .Values.s3.config.options | toYaml | nindent 10 }}

    dso:
      url: {{ .Values.dso.url }}
